version: '3'

services:
  mysql:
    container_name: newsy_db
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    command:
      'mysqld --innodb-flush-method=fsync' # Fix for docker-on-windows-and-mariadb

  wordpress:
    container_name: newsy_wp
    image: wp:newsy
    build: .
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    environment:
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dist:/var/www/html/wp-content/themes/newsy
      - ./wp_uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql
